project:
  type: website
  output-dir: docs

website:
  title: Chris Gomez 
  favicon: turtle.png
  navbar:
    title: false
    logo: turtle-name.png
    logo-alt: "The name 'Chris Gomez' written in black text. Above 'Gomez' is a black turtle icon"
    left:
      - text: HOME
        href: index.qmd
      - text: ABOUT
        href: about.qmd
      - text: PROJECTS
        href: projects.qmd
      - text: UNDERWATER PHOTOGRAPHY
        href: underwater.qmd
      - text: RESUME
        href: Resume.pdf
      - icon: github
        href: https://github.com/christopheregomez 
        
  page-footer: 
    background: light
    left: Copyright 2025, Chris Gomez
    right: This website was built with [{{<fa brands github title = "GitHub octocat logo" >}}](https://github.com/christopheregomez){target=_blank}, [{{< fa brands r-project title = "R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
    - flatly
    - styles.scss
    mainfont: Raleway
    toc: true
    page-layout: full
    
editor: visual

